import SPELLS from './SPELLS';

export const ABILITIES_AFFECTED_BY_HEALING_INCREASES = [
  SPELLS.HOLY_SHOCK_HEAL,
  SPELLS.LIGHT_OF_DAWN_HEAL,
  SPELLS.FLASH_OF_LIGHT,
  SPELLS.JUDGMENT_OF_LIGHT_HEAL,
  SPELLS.LIGHT_OF_THE_MARTYR,
  SPELLS.LIGHTS_HAMMER_HEAL,
  SPELLS.HOLY_PRISM_HEAL,
  SPELLS.HOLY_PRISM_HEAL_DIRECT,
  SPELLS.AURA_OF_MERCY_HEAL,
  // While the following spells don't double dip in healing increases, they gain the same percentual bonus from the transfer
  SPELLS.BEACON_OF_LIGHT_HEAL,
  SPELLS.LEECH,

  // There trinkets are confirmed to also be increased:
  SPELLS.OCEANS_EMBRACE,
  SPELLS.HIGHFATHERS_TIMEKEEPING_HEAL,
  // Didn't check this, but pretty sure it will work the same as the trinkets above:
  SPELLS.GUIDING_HAND,
  // Proof: https://www.warcraftlogs.com/reports/4AVZqJTgyhG2F368/#fight=46&source=4&view=events&pins=2%24Off%24%23244F4B%24auras-gained%24-1%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24true%24216331%24true%24true see the events at 00:03:39.013 and 00:03:40.369.
  SPELLS.AVENGING_CRUSADER_HEAL_NORMAL,
  SPELLS.AVENGING_CRUSADER_HEAL_CRIT,
];

export const ABILITIES_AFFECTED_BY_MASTERY = [
  SPELLS.HOLY_SHOCK_HEAL,
  SPELLS.LIGHT_OF_DAWN_HEAL,
  SPELLS.HOLY_LIGHT,
  SPELLS.FLASH_OF_LIGHT,
  SPELLS.LIGHT_OF_THE_MARTYR,
  SPELLS.HOLY_PRISM_HEAL,
  SPELLS.HOLY_PRISM_HEAL_DIRECT,
  SPELLS.LIGHTS_HAMMER_HEAL,
  SPELLS.JUDGMENT_OF_LIGHT_HEAL,
  SPELLS.BESTOW_FAITH_TALENT,
];

export const BEACON_TRANSFERING_ABILITIES = {
  [SPELLS.HOLY_SHOCK_HEAL]: 1,
  [SPELLS.LIGHT_OF_DAWN_HEAL]: 0.5,
  [SPELLS.HOLY_LIGHT]: 1,
  [SPELLS.FLASH_OF_LIGHT]: 1,
  [SPELLS.HOLY_PRISM_HEAL]: 0.5,
  [SPELLS.HOLY_PRISM_HEAL_DIRECT]: 1,
  [SPELLS.LIGHTS_HAMMER_HEAL]: 0.5,
  [SPELLS.BESTOW_FAITH_TALENT]: 1,
  // While this only beacon transfers with Maraad's, adding it by default shouldn't interfere with anything
  [SPELLS.LIGHT_OF_THE_MARTYR]: 1,
  [SPELLS.AVENGING_CRUSADER_HEAL_NORMAL]: 1,
  [SPELLS.AVENGING_CRUSADER_HEAL_CRIT]: 1,
};

export const BEACON_TYPES = {
  BEACON_OF_FATH: SPELLS.BEACON_OF_FAITH_TALENT,
  DIVINE_PURPOSE_TALENT_HOLY: SPELLS.BEACON_OF_LIGHT_CAST_AND_BUFF,
  BEACON_OF_VIRTUE: SPELLS.BEACON_OF_VIRTUE_TALENT,
};

export const AVENGING_WRATH_HEALING_INCREASE = 0.35;

export const BASE_BEACON_TRANSFER = 0.4;
export const BEACON_OF_FAITH_TRANSFER_REDUCTION = 0.2;
